<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="OCT-JULIEN" failures="2" tests="4" name="Update Profile Test" time="57.444" errors="0" timestamp="2022-07-20T15:37:49 WAT">
  <testcase classname="alphaTests.UpdateProfileTest" name="ValidateUpdateProfile" time="4.027"/>
  <testcase classname="alphaTests.UpdateProfileTest" name="ValidateinvalidUpdateProfile1" time="3.417">
    <failure type="java.lang.AssertionError" message="expected [Invalid Request Data] but found [Update Successful]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Request Data] but found [Update Successful]
at alphaTests.UpdateProfileTest.ValidateUpdateWithInvalidData(UpdateProfileTest.java:106)
at alphaTests.UpdateProfileTest.ValidateinvalidUpdateProfile1(UpdateProfileTest.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidateinvalidUpdateProfile1 -->
  <testcase classname="alphaTests.UpdateProfileTest" name="ValidateinvalidUpdateProfile2" time="3.401">
    <failure type="java.lang.AssertionError" message="expected [Invalid Request Data] but found [Update Successful]">
      <![CDATA[java.lang.AssertionError: expected [Invalid Request Data] but found [Update Successful]
at alphaTests.UpdateProfileTest.ValidateUpdateWithInvalidData(UpdateProfileTest.java:106)
at alphaTests.UpdateProfileTest.ValidateinvalidUpdateProfile2(UpdateProfileTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- ValidateinvalidUpdateProfile2 -->
  <testcase classname="alphaTests.UpdateProfileTest" name="ValidateinvalidUpdateProfile3" time="37.037"/>
</testsuite> <!-- Update Profile Test -->
